### ISSUE TITLE
Implement Survey Participation System

### ISSUE THREAD

**Issue by porowns** [KryptedGaming/kryptedauth#125]
Currently, our surveys have no way of tracking members who complete surveys. Surveys should count for participation.

- continue to outsource to Google forms
- link to survey first, track clicks and log 
- link back to auth with survey code for participation
- keep anonymous of course

**Comment by porowns** [comment]
This is a mostly backend service, and using the admin panel would be sufficient instead of building an entire view for creating surveys.

Should be able to create a link to the survey and store in a Survey model (that should probably go in core), and then have a mechanism for logging survey completion via a URL for that survey that can be attached to the end of the form 

Upon completion, add to survey participants which should fire a SurveyLog event, which can be used for participation

**Comment by Czahrien** [comment]
Everything should be more or less there except for the generation of the actual SurveyLog events - I added a model for those to the records/models.py file but have not added any log records yet.

**Comment by porowns** [comment]
@Czahrien 👏 I can add survey logs if you want, otherwise we can have a talk over signals/tasks on voice when you're free

**Comment by Czahrien** [comment]
@porowns I had written some code adding the SurveyLog records yesterday but did not get around to testing it.

I will be online tonight (6pm-) if you are free
