### ISSUE TITLE
Add Local Time to Events Page (or anywhere UTC is used)

### ISSUE THREAD

**Issue by mawburn** [KryptedGaming/kryptedauth#161]
# Description of issue
On the events page, add in a locale time in addition to the UTC time. Should be easy with Moment.js. 

https://stackoverflow.com/a/32540840/1312971

```JavaScript
var stillUtc = moment.utc(date).toDate();
var local = moment(stillUtc).local().format('YYYY-MM-DD HH:mm:ss');

console.log(local); // 2015-09-13 09:39:27
```

**Comment by porowns** [comment]
Fixed in last release
