### ISSUE TITLE
Installations Help

### ISSUE THREAD

**Issue by CokkocZateki** [KryptedGaming/kryptedauth#234]
Hello
Im looking to have this for my corporation. However im still very new at this and not sure how i can install this onto my server. 
Do you have any other install notes? 

Thank you in advance

**Comment by porowns** [comment]
We're still writing some installation notes since we haven't really released this outside of setting this up for other people. If you drop your Discord we can chat though!

**Comment by CokkocZateki** [comment]
Sure i cant find any Discord invite links

**Comment by porowns** [comment]
It'll be at the top menu of https://kryptedgaming.com/

**Comment by porowns** [comment]
There's also a badge on our README.md

**Comment by CokkocZateki** [comment]
ahh. im in :)
