### ISSUE TITLE
Event System overhaul

### ISSUE THREAD

**Issue by porowns** [KryptedGaming/kryptedauth#94]
Events should be global to the community.

- ~Events are based on a guild group, group=NONE is a community event (NPSI, etc)~
- ~Events should contain: name, description, date, time, voice location, coordinator~
- ~Filter events based on user's guild groups~
- Users can mark whether or not they are going
- ~Users can add/edit/delete events~

Participation Tracking
- Participation tracking is via a 3 digit code, assigned to each event (NOT UNIQUE)
- Alternative participation tracking for all users in a Discord voice channel (difficult)
- Alternative participation tracking for EVE Online fleet

~Create an iCal feed consumable by google calendar.~

**Comment by Czahrien** [comment]
- Generated Event Model
- Events are based on guild group, can be filtered by guild group
- Created a Dashboard for viewing Events
- Created iCal Feed

**Comment by porowns** [comment]
* See if we can clean up add & edit event to look more like view event
* Filter out expired events
*
